//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware_Port
    {
        public int ID { get; set; }
        public int Port_ID { get; set; }
        public int Hardware_ID { get; set; }
    
        public virtual Hardware Hardware { get; set; }
        public virtual Port Port { get; set; }
    }
}
